/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.JOptionPane;

public class RegistrarProfesor extends javax.swing.JFrame {

    ManejoDatos arrayProfesores;

    public RegistrarProfesor() {
    }
    
    public RegistrarProfesor(ManejoDatos arrayProfesores) {
        initComponents();
        setLocationRelativeTo(null); //Establecemos como posicion el centro de la pantalla 
        BloquearCampos();
        this.arrayProfesores = arrayProfesores;
    }
    
    public void LimpiarCampos(){        
        txtNombre.setText("");
        txtApellido1.setText("");
        txtApellido2.setText("");
        txtCorreo.setText("");
        txtSalario.setText("");
        
    }
    
    public void BloquearCampos(){        
        txtNombre.setEnabled(false);
        txtApellido1.setEnabled(false);
        txtApellido2.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtSalario.setEnabled(false);
        comboEstado.setEnabled(false);
        agregar.setEnabled(false);
        buscar.setEnabled(true);
    }
    
    public void DESBloquearCampos(){      
        txtNombre.setEnabled(true);
        txtApellido1.setEnabled(true);
        txtApellido2.setEnabled(true);
        txtCorreo.setEnabled(true);
        txtSalario.setEnabled(true);
        comboEstado.setEnabled(true);
        agregar.setEnabled(true);
        buscar.setEnabled(false);
        txtNombre.requestFocus();
    }
    
    public void mostrarDatos(int cedula){
        
        for (int i=0;i<arrayProfesores.getProfesor().size();i++)
        {
            Profesor profesor = arrayProfesores.getProfesor().get(i);
            if (profesor.getCedula() == cedula) {
                txtNombre.setText(profesor.getNombre());
                txtApellido1.setText(profesor.getApellido1());
                txtApellido2.setText(profesor.getApellido2());
                txtCorreo.setText(profesor.getCorreo());
                txtSalario.setText(String.valueOf(profesor.getSalario()));
                
                if (profesor.isEstado()==true) {
                    comboEstado.setSelectedItem("Activo");
                }
                if (profesor.isEstado()==false) {
                    comboEstado.setSelectedItem("Inactivo");
                }
            }
            else{
            JOptionPane.showMessageDialog(null, "NO existe", "ERROR DE BUSQUEDA",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void editar(){
        
        comboEstado.setEnabled(true);
        String nuevNombre = JOptionPane.showInputDialog(null,"Ingrese el Nuevo Nombre");
        String nuevApe1 = JOptionPane.showInputDialog(null,"Ingrese el Nuevo Primer Apellido");
        String nuevApe2 = JOptionPane.showInputDialog(null,"Ingrese el Nuevo Segundo Apellido");
        String nuevCorreo = JOptionPane.showInputDialog(null,"Ingrese el Nuevo Correo");
        double nuevSalario = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingrese el Nuevo Salario"));
        
        int input = JOptionPane.showConfirmDialog(null, comboEstado,"'¿Cual es el estado del profesor?",JOptionPane.DEFAULT_OPTION);
        String nuevestado = comboEstado.getSelectedItem().toString();
        
        boolean estado = true;
        
        if(nuevestado.equals("Activo")){
            estado = true;
        }
        if(nuevestado.equals("Inactivo")){
            estado = false;
        }
        
        for (int i=0;i<arrayProfesores.getProfesor().size();i++)
        {
            Profesor profesor = arrayProfesores.getProfesor().get(i);
            arrayProfesores.getProfesor().get(i).setNombre(nuevNombre);
            arrayProfesores.getProfesor().get(i).setApellido1(nuevApe1);
            arrayProfesores.getProfesor().get(i).setApellido2(nuevApe2);
            arrayProfesores.getProfesor().get(i).setCorreo(nuevCorreo);
            arrayProfesores.getProfesor().get(i).setSalario(nuevSalario);
            arrayProfesores.getProfesor().get(i).setEstado(estado);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Profesores");

        jLabel2.setText("Numero de cedula:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        agregar.setText("Registrar");
        agregar.setToolTipText("Llene todos los espacios para agregar el nuevo profesor");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.setToolTipText("Debe ingresar un numero de cedula a buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo:");

        jLabel6.setText("Salario x Hora:");

        jLabel8.setText("Estado:");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedula)
                    .addComponent(txtNombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCorreo)
                    .addComponent(txtSalario)
                    .addComponent(comboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregar)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // Registrar
        int cedula=Integer.parseInt(txtCedula.getText());
        String nombre=txtNombre.getText();
        String apellido1=txtApellido1.getText();
        String apellido2=txtApellido2.getText();
        String correo=txtCorreo.getText();
        double salario=Double.parseDouble(txtSalario.getText());
    
        boolean estado = true;
        String tipo = comboEstado.getSelectedItem().toString();

        if(tipo.equals("Activo")){
            estado = true;
        }
        if(tipo.equals("Inactivo")){
            estado = false;
        }

        Profesor profesor = new Profesor(cedula, nombre, apellido1, apellido2, correo, salario, estado);
        arrayProfesores.getProfesor().add(profesor);

        JOptionPane.showMessageDialog(null, "Profesor agregado con exito");
        txtCedula.setText("");
        LimpiarCampos();
        BloquearCampos();

    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        int cedula=Integer.parseInt(txtCedula.getText());

        for (int i=0;i<arrayProfesores.getProfesor().size();i++)
        {
            Profesor xprofesor = arrayProfesores.getProfesor().get(i);
            if (xprofesor.getCedula() == cedula) {
                JOptionPane.showMessageDialog(null, "El Profesor ya existe","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                mostrarDatos(cedula);
                BloquearCampos();
                int resp = JOptionPane.showConfirmDialog(null, "¿Desea Editar Datos de Este Profesor?", "EDITAR", JOptionPane.YES_NO_OPTION);
                if(resp==JOptionPane.YES_OPTION){
                    editar();
                    mostrarDatos(cedula);
                    JOptionPane.showMessageDialog(null, "Datos Editados con Exito");
                }
                if(resp==JOptionPane.NO_OPTION){
                    txtCedula.setText("");
                    LimpiarCampos();
                }
            }
            else{
                DESBloquearCampos();
                JOptionPane.showMessageDialog(null, "El profesor NO existe puede agregarlo","VALIDANDO DATOS",JOptionPane.INFORMATION_MESSAGE);
                LimpiarCampos();
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
